# Minecraft
minecraft_version=1.21.11

# Fabric
loader_version=0.19.5
fabric_api_version=0.141.6+1.21.11

# Mod
mod_version=1.0.0
maven_group=com.alihan.hotbarscale
archives_base_name=hotbar-scale

# Mod Menu
modmenu_version=Tyk71iSw
cloth_config_version=xuX40TN5
placeholder_api_version=qxjzQ9xY

# Gradle
org.gradle.jvmargs=-Xmx2G